Users can sign up.
ryanchangyeolshin/mistory pull request #4
Opened 2017-11-06 23:01 UTC by ryanchangyeolshin

Hey Tim. I know you said to not deal with the backend features until later, but I will avoid doing so going forward.

2017-11-06 23:46 UTC, thebearingedge requested changes

2017-11-06 23:46 UTC, thebearingedge commented on client/app.js
> +    this.userFormStyle = { margin: '50px 0', padding: '20px 30px', textAlign: 'center' }
It would be better to move this style object to the `UserForm` component directly.

2017-11-06 23:46 UTC, thebearingedge commented on client/users-form.js
> +        /><br />
If you want elements to stack, it's best to wrap them in a block-level element instead of throwing in `<br/>` elements.

2017-11-06 23:46 UTC, thebearingedge commented on test/users-gateway.test.js
> +      expect(password).to.equal(testUser.password)
You probably don't want to return their password, right?

2017-11-06 23:46 UTC, thebearingedge commented on test/users-router.test.js
> +      expect(data).to.include(testUser.password)
Probably should omit their password, right?

2017-11-07 18:46 UTC, thebearingedge approved these changes
Very clean.

2017-11-08 17:59 UTC, thebearingedge commented
Did you mean to merge this?

2017-11-08 18:00 UTC, ryanchangyeolshin commented
Forgot to merge this. Thank you.

2017-11-08 18:00 UTC, merged